#!/bin/bash

# Read the URL of the website you want to check
read -t 30 -p "Enter the URL of the website you want to check: " url

# Get the md5sum of the current curl command
current_md5=$(curl -s $url | md5sum)

# Get the md5sum of the previous curl command
previous_md5=$(cat logfile)

# Compare the md5sums
if [ "$current_md5" == "$previous_md5" ]; then
    echo "Website not changed"
else
    echo "Website changed"
fi

# Save the md5sum of the current curl command to logfile
echo "$current_md5" > logfile
